/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AgbRouteImport } from './routes/agb'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as KaufenRouteImport } from './routes/kaufen'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PasswortVergessenRouteImport } from './routes/passwort-vergessen'
import { Route as PasswortZuruecksetzenRouteImport } from './routes/passwort-zuruecksetzen'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as TeilHinzufuegenRouteImport } from './routes/teil-hinzufuegen'
import { Route as ProfilHinzufuegenRouteImport } from './routes/profil_.hinzufuegen'
import { Route as ProfilSchrankIndexRouteImport } from './routes/profil_.schrank.index'
import { Route as ProfilSchrankIdRouteImport } from './routes/profil_.schrank.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AgbRoute = AgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const KaufenRoute = KaufenRouteImport.update({
  id: '/kaufen',
  path: '/kaufen',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswortVergessenRoute = PasswortVergessenRouteImport.update({
  id: '/passwort-vergessen',
  path: '/passwort-vergessen',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswortZuruecksetzenRoute = PasswortZuruecksetzenRouteImport.update({
  id: '/passwort-zuruecksetzen',
  path: '/passwort-zuruecksetzen',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const TeilHinzufuegenRoute = TeilHinzufuegenRouteImport.update({
  id: '/teil-hinzufuegen',
  path: '/teil-hinzufuegen',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilHinzufuegenRoute = ProfilHinzufuegenRouteImport.update({
  id: '/profil_/hinzufuegen',
  path: '/profil/hinzufuegen',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilSchrankIndexRoute = ProfilSchrankIndexRouteImport.update({
  id: '/profil_/schrank/',
  path: '/profil/schrank/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilSchrankIdRoute = ProfilSchrankIdRouteImport.update({
  id: '/profil_/schrank/$id',
  path: '/profil/schrank/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/agb': typeof AgbRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kaufen': typeof KaufenRoute
  '/login': typeof LoginRoute
  '/passwort-vergessen': typeof PasswortVergessenRoute
  '/passwort-zuruecksetzen': typeof PasswortZuruecksetzenRoute
  '/profil': typeof ProfilRoute
  '/teil-hinzufuegen': typeof TeilHinzufuegenRoute
  '/profil/hinzufuegen': typeof ProfilHinzufuegenRoute
  '/profil/schrank/$id': typeof ProfilSchrankIdRoute
  '/profil/schrank/': typeof ProfilSchrankIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/agb': typeof AgbRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kaufen': typeof KaufenRoute
  '/login': typeof LoginRoute
  '/passwort-vergessen': typeof PasswortVergessenRoute
  '/passwort-zuruecksetzen': typeof PasswortZuruecksetzenRoute
  '/profil': typeof ProfilRoute
  '/teil-hinzufuegen': typeof TeilHinzufuegenRoute
  '/profil/hinzufuegen': typeof ProfilHinzufuegenRoute
  '/profil/schrank/$id': typeof ProfilSchrankIdRoute
  '/profil/schrank': typeof ProfilSchrankIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/agb': typeof AgbRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kaufen': typeof KaufenRoute
  '/login': typeof LoginRoute
  '/passwort-vergessen': typeof PasswortVergessenRoute
  '/passwort-zuruecksetzen': typeof PasswortZuruecksetzenRoute
  '/profil': typeof ProfilRoute
  '/teil-hinzufuegen': typeof TeilHinzufuegenRoute
  '/profil_/hinzufuegen': typeof ProfilHinzufuegenRoute
  '/profil_/schrank/$id': typeof ProfilSchrankIdRoute
  '/profil_/schrank/': typeof ProfilSchrankIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/agb'
    | '/datenschutz'
    | '/impressum'
    | '/kaufen'
    | '/login'
    | '/passwort-vergessen'
    | '/passwort-zuruecksetzen'
    | '/profil'
    | '/teil-hinzufuegen'
    | '/profil/hinzufuegen'
    | '/profil/schrank/$id'
    | '/profil/schrank/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/agb'
    | '/datenschutz'
    | '/impressum'
    | '/kaufen'
    | '/login'
    | '/passwort-vergessen'
    | '/passwort-zuruecksetzen'
    | '/profil'
    | '/teil-hinzufuegen'
    | '/profil/hinzufuegen'
    | '/profil/schrank/$id'
    | '/profil/schrank'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/agb'
    | '/datenschutz'
    | '/impressum'
    | '/kaufen'
    | '/login'
    | '/passwort-vergessen'
    | '/passwort-zuruecksetzen'
    | '/profil'
    | '/teil-hinzufuegen'
    | '/profil_/hinzufuegen'
    | '/profil_/schrank/$id'
    | '/profil_/schrank/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AgbRoute: typeof AgbRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  KaufenRoute: typeof KaufenRoute
  LoginRoute: typeof LoginRoute
  PasswortVergessenRoute: typeof PasswortVergessenRoute
  PasswortZuruecksetzenRoute: typeof PasswortZuruecksetzenRoute
  ProfilRoute: typeof ProfilRoute
  TeilHinzufuegenRoute: typeof TeilHinzufuegenRoute
  ProfilHinzufuegenRoute: typeof ProfilHinzufuegenRoute
  ProfilSchrankIdRoute: typeof ProfilSchrankIdRoute
  ProfilSchrankIndexRoute: typeof ProfilSchrankIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agb': {
      id: '/agb'
      path: '/agb'
      fullPath: '/agb'
      preLoaderRoute: typeof AgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kaufen': {
      id: '/kaufen'
      path: '/kaufen'
      fullPath: '/kaufen'
      preLoaderRoute: typeof KaufenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passwort-vergessen': {
      id: '/passwort-vergessen'
      path: '/passwort-vergessen'
      fullPath: '/passwort-vergessen'
      preLoaderRoute: typeof PasswortVergessenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passwort-zuruecksetzen': {
      id: '/passwort-zuruecksetzen'
      path: '/passwort-zuruecksetzen'
      fullPath: '/passwort-zuruecksetzen'
      preLoaderRoute: typeof PasswortZuruecksetzenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teil-hinzufuegen': {
      id: '/teil-hinzufuegen'
      path: '/teil-hinzufuegen'
      fullPath: '/teil-hinzufuegen'
      preLoaderRoute: typeof TeilHinzufuegenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil_/hinzufuegen': {
      id: '/profil_/hinzufuegen'
      path: '/profil/hinzufuegen'
      fullPath: '/profil/hinzufuegen'
      preLoaderRoute: typeof ProfilHinzufuegenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil_/schrank/': {
      id: '/profil_/schrank/'
      path: '/profil/schrank'
      fullPath: '/profil/schrank/'
      preLoaderRoute: typeof ProfilSchrankIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil_/schrank/$id': {
      id: '/profil_/schrank/$id'
      path: '/profil/schrank/$id'
      fullPath: '/profil/schrank/$id'
      preLoaderRoute: typeof ProfilSchrankIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AgbRoute: AgbRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  KaufenRoute: KaufenRoute,
  LoginRoute: LoginRoute,
  PasswortVergessenRoute: PasswortVergessenRoute,
  PasswortZuruecksetzenRoute: PasswortZuruecksetzenRoute,
  ProfilRoute: ProfilRoute,
  TeilHinzufuegenRoute: TeilHinzufuegenRoute,
  ProfilHinzufuegenRoute: ProfilHinzufuegenRoute,
  ProfilSchrankIdRoute: ProfilSchrankIdRoute,
  ProfilSchrankIndexRoute: ProfilSchrankIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
